config/routes.rb
Rails.application.routes.draw do

  resources :tweets

  root "tweets#index"
  get "tweets" => "tweets#tweets"
  get "show" => "tweets#show"

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	helper_method :tweets

	def index
	end

	def tweets
		tweets = Tweet.all
	end

	def show
		@tweet = tweets.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Tweets/index.html.erb
<h1>Welcome to Super Basic Twitter for Dummies</h1>

<h2><div>
<%= link_to "Check out Tweets Here", tweets_path%>
</div></h2>


<body>

<% tweets.each do |tweet| %>
<table>
	<tr>
		<td> <b><%= tweet.content %></b></td>
		<td><%= tweet.handle %></td>
		<td><%= link_to "Show", tweet %></td>
	</tr>

<%end%>

</table>

</body>


app/views/Tweets/show.html.erb
<h1> Tweet by <%= @tweet.handle %></h1>

<body>
<table>
	<tr>
		<td> <b><%= @tweet.content %></b></td>
	</tr>

</table>

</body>

app/views/Tweets/tweets.html.erb
<h1>Most Recent Tweets</h1>

<body>

<% tweets.each do |tweet| %>
<table>
	<tr>
		<td> <b><%= tweet.content %></b></td>
		<td><%= tweet.handle %></td>
		<td><%= link_to "Show", tweet %></td>
	</tr>

<%end%>

</table>

</body>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterhw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div>
<%= link_to "Home", root_path%>
<%= link_to "Tweets", tweets_path%>
</div>


<%= yield %>

</body>
</html>